#!/bin/bash
################################################################################
#
#   Hourly cron job for redundancy
#
################################################################################

# ot-project-sync # project sync should be done as a part of deployment procedure
ot-attachments-sync # Keep attachments less than an hour old.

## End
exit 0 # 0 = success
