#!/bin/bash
################################################################################
#
#   Monthly cron job for redundancy
#
################################################################################

ma-sync-from-source # Get everything once a month just in case.

## End
exit 0 # 0 = success
